---
- name: AUTOMTIC BACKUP OF RUNNING CONFIG
  hosts: all
  gather_facts: false
  connection: local
  
  tasks:
   - name: DYSPLAYING THE RUNNING-CONFIG
     ios_command:
      commands:
       - show run
     register: config
   - name: SAVE OUTPUT TO ./backups/
     copy:
      content: "{{ config.stdout[0] }}"
      dest: "/home/tridog/show_run_{{ inventory_hostname }}.txt"
