---
- name: Conf_Spoke
  hosts: all
  gather_facts: false
  connection: local
  
  tasks:
   - name: Config_Tunnle0 
     ios_config:
       parents:
         - int tunnel0 
       lines: 
         - no ip redirects 
         - ip address {{tun_address}} 255.255.255.0 
         - ip mtu 1440 
         - ip nhrp authentication cisDMVPN 
         - ip nhrp map {{hub_tun_address}} {{hub_address}} 
         - ip nhrp map multicast {{hub_address}} 
         - ip nhrp network-id {{net_id}} 
         - ip nhrp nhs {{hub_tun_address}} 
         - ip ospf network broadcast 
         - ip ospf priority 0 
         - tunnel source Ethernet {{tun_int}}
         - tunnel mode gre multipoint 
         - tunnel key {{tun_key}} 